### PR TITLE
改为支持https的版本

### PR DESCRIPTION
**Pull request by A-Cepheus**
修改协议为wss，调整为一个顺眼的logo

### CODE REVIEW

**Comment by A-Cepheus** [comment]
测试通过

**Comment by Quadrubo** [comment]
english please, you can't just delete the whole english readme and expect me to merge

**Comment by A-Cepheus** [comment]
> english please, you can't just delete the whole english readme and expect me to merge

sorry, I closed it.

**Comment by Quadrubo** [comment]
no problem, if you make a new one without changing the whole readme and stuff i'll take a look at it

**Comment by A-Cepheus** [comment]
> no problem, if you make a new one without changing the whole readme and stuff i'll take a look at it

This is not a recommended change at present (because the certificate is used). I will pull new requests in the future when the certificate is not required or HTTP / HTTPS can be supported at the same time. :)

**Pull request closed without merging**
